// Data feed for the /admin/ portal's "Related service" / "Related guide"
// dropdowns — generated by the regular site build (npm run build), so it's
// always in sync with whatever services/blog posts are actually live. Not
// HTML, so it's naturally excluded from the sitemap (which only walks
// index.html files) and llms.txt.
import { getCollection } from 'astro:content';
import type { APIContext } from 'astro';
import { ALL_SERVICE_SLUGS } from '../utils/content';

export async function GET(_context: APIContext) {
  const now = new Date();

  const services = await Promise.all(
    ALL_SERVICE_SLUGS.map(async (slug) => {
      const entry = await getCollection('services', (e) => e.id === slug);
      const title = entry[0]?.data.title || slug;
      return { slug, title };
    })
  );

  const posts = (await getCollection('blog'))
    .filter((p) => p.data.published && p.data.date <= now)
    .sort((a, b) => b.data.date.getTime() - a.data.date.getTime())
    .map((p) => ({ slug: p.id, title: p.data.title }));

  return new Response(JSON.stringify({ services, posts }), {
    headers: { 'Content-Type': 'application/json' },
  });
}
